pipeline {
    agent any

    tools {
        dotnetsdk 'dotnet9'
    }

    environment {
        SCANNER_HOME    = tool 'sonar-scanner'
        DOCKER_NAME     = 'ravi6198/cartservice'
        IMAGE_NAME      = 'cartservice'
        IMAGE_TAG       = "${BUILD_NUMBER}"

        SERVICE_DIR     = 'src/cartservice'

        SONAR_TOKEN_ID  = 'sonar-token'
        DOCKER_CREDS_ID = 'docker-cred'
        COSIGN_KEY_ID   = 'cosign-private-key'
    }

    stages {

        stage("Clean Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Git Checkout") {
            steps {
                git branch: 'main',
                    url: 'https://github.com/raviprakash96520/Google-microservices-devsecops-project.git'
            }
        }


        stage('Secret Scan (GitLeaks)') {
            steps {
                echo "Checking secrets..."
                sh "gitleaks detect --source=${env.SERVICE_DIR} --verbose || true"
            }
        }


        stage('License Scan') {
            steps {
                dir("${env.SERVICE_DIR}") {
                    echo "Checking NuGet license compliance..."
                }
            }
        }


        stage("Build & Test Execution") {
            steps {
                dir("${env.SERVICE_DIR}/src") {
                    sh '''
                    dotnet restore
                    dotnet build --no-incremental
                    dotnet test --logger:trx || true
                    '''
                }
            }
        }


        stage("SonarQube Analysis") {
            steps {
                dir("${env.SERVICE_DIR}") {

                    withSonarQubeEnv('sonar-server') {

                        sh '''
                        dotnet tool install --global dotnet-sonarscanner || true
                        export PATH="$PATH:$HOME/.dotnet/tools"

                        dotnet sonarscanner begin \
                        /k:"cartservice" \
                        /d:sonar.host.url=$SONAR_HOST_URL \
                        /d:sonar.token=$SONAR_AUTH_TOKEN

                        dotnet build src/cartservice.csproj

                        dotnet sonarscanner end \
                        /d:sonar.token=$SONAR_AUTH_TOKEN
                        '''
                    }
                }
            }
        }


        stage("Quality Gate Check") {
            steps {
                script {
                    timeout(time: 7, unit: 'MINUTES') {
                        waitForQualityGate abortPipeline: true,
                        credentialsId: "${SONAR_TOKEN_ID}"
                    }
                }
            }
        }

        //         stage("SCA Dependency Scan") {
        //     steps {
        //         dir("${env.SERVICE_DIR}") {
        //             dependencyCheck additionalArguments: '''
        //                 --scan ./
        //                 --format XML
        //                 --out dependency-check-report.xml
        //             ''',
        //             odcInstallation: 'dp-check'
        //         }
        //     }
        //     post {
        //         always {
        //             archiveArtifacts "${env.SERVICE_DIR}/dependency-check-report.xml"
        //         }
        //     }
        // }


        stage('IaC Configuration Scan') {
            steps {
                dir("${env.SERVICE_DIR}") {
                    echo "Checking configuration files..."
                    sh 'trivy config . --severity HIGH,CRITICAL > iac-report.txt || true'
                }
            }
            post {
                always {
                    archiveArtifacts "${env.SERVICE_DIR}/iac-report.txt"
                }
            }
        }


        stage("Trivy File Scan") {
            steps {
                dir("${env.SERVICE_DIR}") {
                    sh '''
                    trivy fs . \
                    --severity CRITICAL,HIGH \
                    --exit-code 1 \
                    --scanners vuln,misconfig,secret \
                    > trivy-fs-report.txt || true
                    '''
                }
            }
            post {
                always {
                    archiveArtifacts "${env.SERVICE_DIR}/trivy-fs-report.txt"
                }
            }
        }


        stage("Build Docker Image") {
            steps {
                dir("${env.SERVICE_DIR}/src") {
                    script {

                        env.FINAL_TAG = "${DOCKER_NAME}:${IMAGE_TAG}"

                        sh "docker rmi -f ${IMAGE_NAME} ${env.FINAL_TAG} || true"

                        sh "docker build -t ${IMAGE_NAME} ."

                        sh "docker tag ${IMAGE_NAME} ${env.FINAL_TAG}"
                    }
                }
            }
        }


        stage("Generate SBOM Manifest") {
            steps {
                dir("${env.SERVICE_DIR}") {
                    script {

                        echo "Generating SBOM..."

                        sh """
                        trivy image \
                        --format cyclonedx \
                        --output sbom.json \
                        ${IMAGE_NAME}
                        """
                    }
                }
            }
            post {
                always {
                    archiveArtifacts "${env.SERVICE_DIR}/sbom.json"
                }
            }
        }


        stage("Trivy Scan Image Layer") {
            steps {
                dir("${env.SERVICE_DIR}") {

                    script {

                        sh """
                        trivy image \
                        -f json \
                        -o trivy-image-cart.json \
                        ${env.FINAL_TAG}


                        trivy image \
                        -f table \
                        -o trivy-image-cart.txt \
                        ${env.FINAL_TAG}
                        """
                    }
                }
            }
            post {
                always {
                    archiveArtifacts "${env.SERVICE_DIR}/trivy-image-cart.json"
                    archiveArtifacts "${env.SERVICE_DIR}/trivy-image-cart.txt"
                }
            }
        }


        stage("Push to DockerHub Registry") {

            steps {

                dir("${env.SERVICE_DIR}") {

                    script {

                        withCredentials([usernamePassword(
                            credentialsId: "${DOCKER_CREDS_ID}",
                            usernameVariable: 'dockeruser',
                            passwordVariable: 'dockerpwd'
                        )]) {

                            sh "docker login -u ravi6198 -p ${dockerpwd}"

                            sh "docker push ${env.FINAL_TAG}"
                        }
                    }
                }
            }
        }


        stage("Sign Container Image") {

            steps {

                dir("${env.SERVICE_DIR}") {

                    script {

                        echo "Cosign signing placeholder..."

                        // Future:
                        // cosign sign --key cosign.key ${env.FINAL_TAG}

                    }
                }
            }
        }
    }


    post {

        always {

            dir("${env.SERVICE_DIR}") {

                script {

                    def buildStatus = currentBuild.currentResult

                    def buildUser =
                    currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]?.userId
                    ?: 'Github User'


                    emailext (

                        subject:
                        "Pipeline ${buildStatus}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",


                        body:
                        """
                        <p>Cartservice Component Google-Shop DevSecOps pipeline status report.</p>

                        <p>Project: ${env.SERVICE_DIR}</p>

                        <p>Build Number: ${env.BUILD_NUMBER}</p>

                        <p>Build Status: ${buildStatus}</p>

                        <p>Started by: ${buildUser}</p>

                        <p>Build URL:
                        <a href="${env.BUILD_URL}">
                        ${env.BUILD_URL}
                        </a>
                        </p>
                        """,


                        to: 'ravireddy6198@gmail.com',

                        from: 'ravireddy6198@gmail.com',

                        mimeType: 'text/html',

                        attachmentsPattern:
                        'trivy-fs-report.txt,trivy-image-cart.json,trivy-image-cart.txt,dependency-check-report.xml,sbom.json,iac-report.txt'
                    )
                }
            }


            cleanWs()
        }
    }
}